### PR TITLE
Update data URL for 2016 campaign

### PR DESCRIPTION
**Pull request by cadecairos**
Hey @Archaeopteryx! I hope all is well!

I'd like to revive this addon for the fundraising team and community, so I've gone and updated the data source URL.

Could you review and merge, and possibly update the app in the addon store?

(a lot to ask, sorry :))

### CODE REVIEW

**Review by Archaeopteryx — APPROVED** [review]

**Comment by Archaeopteryx** [comment]
Thanks,  new version has been approved on addons.mozilla.org and existing installations should update in 24 hours. https://addons.mozilla.org/firefox/addon/counter-for-mozillas-eoy-fund/

**Comment by cadecairos** [comment]
Thanks a bunch :fireworks:

**Comment by lovegushwa** [comment]
@Archaeopteryx thank you !!

**Comment by HPaulJohnson** [comment]
@Archaeopteryx this is great - thank you!

**Pull request merged**
